### PR TITLE
fix: Fixed oci based shell script

### PR DESCRIPTION
**Pull request by marthydavid**
Somehow the name/entry cut in the shell script was not parsing correctly the config.
I've rerun several times locally the script deleting schemas for other OCI based chart and looked like it works.
I don't know if I should remove the scheduled commits or not.

I hape this PR is okay.

### CODE REVIEW

**Comment by CodeReaper** [comment]
We should let the automation handle adding and updating the schema directory, meaning we should not include schema updates in PRs.

However more importantly do you have any ideas on how to add local tests that checks OCI works?

**Comment by marthydavid** [comment]
I've removed the commits created by the schedule, and disabled my fork's schedule.

**Comment by marthydavid** [comment]
#22 has testing implemented on a high level.

**Comment by CodeReaper** [comment]
#23 should correct the error with OCI. Do you know if the values file input in this pull request is actually required for `logging-operator`?

**Comment by marthydavid** [comment]
Yes that's needed

**Comment by CodeReaper** [comment]
I took a look at it and I do not entirely understand why, but it does not seem like it is needed.

These two yields the same CRDs:
```sh
helm template --include-crds oci://ghcr.io/kube-logging/helm-charts/logging-operator --version 4.6.0 | yq 'select(.kind == "CustomResourceDefinition")' | grep '^  name: '
Pulled: ghcr.io/kube-logging/helm-charts/logging-operator:4.6.0
Digest: sha256:b00bc878447747ffeaff85ea3772ed6c70e4315f7d9e975dd3830494d92b04db
  name: eventtailers.logging-extensions.banzaicloud.io
  name: hosttailers.logging-extensions.banzaicloud.io
  name: clusterflows.logging.banzaicloud.io
  name: clusteroutputs.logging.banzaicloud.io
  name: flows.logging.banzaicloud.io
  name: fluentbitagents.logging.banzaicloud.io
  name: fluentdconfigs.logging.banzaicloud.io
  name: loggingroutes.logging.banzaicloud.io
  name: loggings.logging.banzaicloud.io
  name: nodeagents.logging.banzaicloud.io
  name: outputs.logging.banzaicloud.io
  name: syslogngclusterflows.logging.banzaicloud.io
  name: syslogngclusteroutputs.logging.banzaicloud.io
  name: syslogngconfigs.logging.banzaicloud.io
  name: syslogngflows.logging.banzaicloud.io
  name: syslogngoutputs.logging.banzaicloud.io

# note --include-crds is not used here
echo 'createCustomResource: true' > values && helm template oci://ghcr.io/kube-logging/helm-charts/logging-operator --version 4.6.0 -f values | yq 'select(.kind == "CustomResourceDefinition")' | grep '^  name: '
Pulled: ghcr.io/kube-logging/helm-charts/logging-operator:4.6.0
Digest: sha256:b00bc878447747ffeaff85ea3772ed6c70e4315f7d9e975dd3830494d92b04db
  name: eventtailers.logging-extensions.banzaicloud.io
  name: hosttailers.logging-extensions.banzaicloud.io
  name: clusterflows.logging.banzaicloud.io
  name: clusteroutputs.logging.banzaicloud.io
  name: flows.logging.banzaicloud.io
  name: fluentbitagents.logging.banzaicloud.io
  name: fluentdconfigs.logging.banzaicloud.io
  name: loggingroutes.logging.banzaicloud.io
  name: loggings.logging.banzaicloud.io
  name: nodeagents.logging.banzaicloud.io
  name: outputs.logging.banzaicloud.io
  name: syslogngclusterflows.logging.banzaicloud.io
  name: syslogngclusteroutputs.logging.banzaicloud.io
  name: syslogngconfigs.logging.banzaicloud.io
  name: syslogngflows.logging.banzaicloud.io
  name: syslogngoutputs.logging.banzaicloud.io
```

However using both the include option and the values files yields each CRD twice:
```sh
echo 'createCustomResource: true' > values && helm template --include-crds oci://ghcr.io/kube-logging/helm-charts/logging-operator --version 4.6.0 -f values | yq 'select(.kind == "CustomResourceDefinition")' | grep '^  name: '
Pulled: ghcr.io/kube-logging/helm-charts/logging-operator:4.6.0
Digest: sha256:b00bc878447747ffeaff85ea3772ed6c70e4315f7d9e975dd3830494d92b04db
  name: eventtailers.logging-extensions.banzaicloud.io
  name: hosttailers.logging-extensions.banzaicloud.io
  name: clusterflows.logging.banzaicloud.io
  name: clusteroutputs.logging.banzaicloud.io
  name: flows.logging.banzaicloud.io
  name: fluentbitagents.logging.banzaicloud.io
  name: fluentdconfigs.logging.banzaicloud.io
  name: loggingroutes.logging.banzaicloud.io
  name: loggings.logging.banzaicloud.io
  name: nodeagents.logging.banzaicloud.io
  name: outputs.logging.banzaicloud.io
  name: syslogngclusterflows.logging.banzaicloud.io
  name: syslogngclusteroutputs.logging.banzaicloud.io
  name: syslogngconfigs.logging.banzaicloud.io
  name: syslogngflows.logging.banzaicloud.io
  name: syslogngoutputs.logging.banzaicloud.io
  name: eventtailers.logging-extensions.banzaicloud.io # it starts repeating here
  name: hosttailers.logging-extensions.banzaicloud.io
  name: clusterflows.logging.banzaicloud.io
  name: clusteroutputs.logging.banzaicloud.io
  name: flows.logging.banzaicloud.io
  name: fluentbitagents.logging.banzaicloud.io
  name: fluentdconfigs.logging.banzaicloud.io
  name: loggingroutes.logging.banzaicloud.io
  name: loggings.logging.banzaicloud.io
  name: nodeagents.logging.banzaicloud.io
  name: outputs.logging.banzaicloud.io
  name: syslogngclusterflows.logging.banzaicloud.io
  name: syslogngclusteroutputs.logging.banzaicloud.io
  name: syslogngconfigs.logging.banzaicloud.io
  name: syslogngflows.logging.banzaicloud.io
  name: syslogngoutputs.logging.banzaicloud.io
```

I also checked that each repetition is identical.

**Comment by CodeReaper** [comment]
I am closing this PR - if there is something that still needs to be corrected, let us do so in a fresh issue or PR.

**Comment by marthydavid** [comment]
Thanks, everything is sorted out

**Pull request closed without merging**
